import Foundation

public enum SegmentSource: String, Codable, Sendable {
    /// Captured via SCStream (system audio mix — remote participants in a meeting).
    case remote
    /// Captured via the local microphone (the user's own voice).
    case local
}

public struct TranscriptSegment: Codable, Equatable, Sendable {
    public let startTime: Double
    public let endTime: Double
    public let text: String
    public let source: SegmentSource
    /// Diarized speaker index (e.g. Deepgram speaker 0/1/…). Nil for OpenAI
    /// Whisper output, which only carries the binary `source` tag.
    public let speakerID: Int?

    public init(
        startTime: Double,
        endTime: Double,
        text: String,
        source: SegmentSource = .remote,
        speakerID: Int? = nil
    ) {
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
        self.source = source
        self.speakerID = speakerID
    }

    private enum CodingKeys: String, CodingKey {
        case startTime, endTime, text, source, speakerID
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.startTime = try c.decode(Double.self, forKey: .startTime)
        self.endTime = try c.decode(Double.self, forKey: .endTime)
        self.text = try c.decode(String.self, forKey: .text)
        // Pre-multi-source persisted segments have no `source`; treat as remote (system audio).
        self.source = try c.decodeIfPresent(SegmentSource.self, forKey: .source) ?? .remote
        self.speakerID = try c.decodeIfPresent(Int.self, forKey: .speakerID)
    }
}

public struct TranscriptSession: Codable, Equatable, Sendable {
    public enum Status: String, Codable, Sendable {
        case recording, chunking, transcribing, completed, cancelled, failed
    }

    public let id: UUID
    public var title: String
    public let startedAt: Date
    public var endedAt: Date?
    public var status: Status
    public var chunksTotal: Int
    public var chunksCompleted: Int
    public var segments: [TranscriptSegment]
    public var audioRetained: Bool
    public var failureReason: String?
    /// Markdown summary generated post-transcription by `MeetingSummarizer`.
    /// Nil when summary is disabled, the call failed, or the transcript was
    /// generated by an older app version.
    public var summary: String?

    public init(
        id: UUID,
        title: String,
        startedAt: Date,
        endedAt: Date?,
        status: Status,
        chunksTotal: Int,
        chunksCompleted: Int,
        segments: [TranscriptSegment],
        audioRetained: Bool,
        failureReason: String? = nil,
        summary: String? = nil
    ) {
        self.id = id
        self.title = title
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.status = status
        self.chunksTotal = chunksTotal
        self.chunksCompleted = chunksCompleted
        self.segments = segments
        self.audioRetained = audioRetained
        self.failureReason = failureReason
        self.summary = summary
    }

    private enum CodingKeys: String, CodingKey {
        case id, title, startedAt, endedAt, status, chunksTotal, chunksCompleted,
             segments, audioRetained, failureReason, summary
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try c.decode(UUID.self, forKey: .id)
        self.title = try c.decode(String.self, forKey: .title)
        self.startedAt = try c.decode(Date.self, forKey: .startedAt)
        self.endedAt = try c.decodeIfPresent(Date.self, forKey: .endedAt)
        self.status = try c.decode(Status.self, forKey: .status)
        self.chunksTotal = try c.decode(Int.self, forKey: .chunksTotal)
        self.chunksCompleted = try c.decode(Int.self, forKey: .chunksCompleted)
        self.segments = try c.decode([TranscriptSegment].self, forKey: .segments)
        self.audioRetained = try c.decode(Bool.self, forKey: .audioRetained)
        self.failureReason = try c.decodeIfPresent(String.self, forKey: .failureReason)
        // Pre-summary persisted sessions have no `summary`; treat as nil.
        self.summary = try c.decodeIfPresent(String.self, forKey: .summary)
    }
}

public extension Notification.Name {
    static let meetingTranscriptStoreDidChange =
        Notification.Name("vox.meetingTranscriptStoreDidChange")
}

public final class MeetingTranscriptStore {
    /// Transcript mutations are process-wide because the app creates several
    /// store instances that all point at the same on-disk root.
    private static let operationLock = NSRecursiveLock()

    public let rootDirectory: URL
    private let encoder: JSONEncoder
    private let decoder: JSONDecoder

    /// Default location: ~/Library/Application Support/Vox/MeetingTranscripts
    public static func defaultRoot() -> URL {
        let support = FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first!
        return support
            .appendingPathComponent("Vox", isDirectory: true)
            .appendingPathComponent("MeetingTranscripts", isDirectory: true)
    }

    public init(rootDirectory: URL = MeetingTranscriptStore.defaultRoot()) {
        self.rootDirectory = rootDirectory
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        self.encoder = encoder
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        self.decoder = decoder
    }

    public func sessionDirectory(id: UUID) -> URL {
        rootDirectory.appendingPathComponent(id.uuidString, isDirectory: true)
    }

    public func audioFile(id: UUID) -> URL {
        sessionDirectory(id: id).appendingPathComponent("audio.m4a")
    }

    /// Local mic recording captured in parallel with system audio.
    public func micFile(id: UUID) -> URL {
        sessionDirectory(id: id).appendingPathComponent("mic.m4a")
    }

    /// CoreAudio process-tap output for VoIP apps (Phone/FaceTime) whose
    /// audio path SCStream cannot see. Optional — only present when a target
    /// app was running at meeting start on macOS 14.4+.
    public func phoneFile(id: UUID) -> URL {
        sessionDirectory(id: id).appendingPathComponent("phone.m4a")
    }

    public func chunksDirectory(id: UUID) -> URL {
        sessionDirectory(id: id).appendingPathComponent("chunks", isDirectory: true)
    }

    /// Per-source chunk directory keeps system and mic chunk ordering independent.
    public func chunksDirectory(id: UUID, source: SegmentSource) -> URL {
        let name = source == .local ? "chunks-mic" : "chunks-system"
        return sessionDirectory(id: id).appendingPathComponent(name, isDirectory: true)
    }

    private func transcriptFile(id: UUID) -> URL {
        sessionDirectory(id: id).appendingPathComponent("transcript.json")
    }

    public func save(_ session: TranscriptSession) throws {
        try withOperationLock {
            try saveWithoutNotification(session)
        }
        NotificationCenter.default.post(name: .meetingTranscriptStoreDidChange, object: nil)
    }

    private func saveWithoutNotification(_ session: TranscriptSession) throws {
        let dir = sessionDirectory(id: session.id)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let data = try encoder.encode(session)
        try data.write(to: transcriptFile(id: session.id), options: .atomic)
    }

    public func load(id: UUID) -> TranscriptSession? {
        withOperationLock {
            loadWithoutLock(id: id)
        }
    }

    private func loadWithoutLock(id: UUID) -> TranscriptSession? {
        guard let data = try? Data(contentsOf: transcriptFile(id: id)) else {
            return nil
        }
        return try? decoder.decode(TranscriptSession.self, from: data)
    }

    /// Atomically checks and updates an existing transcript. `delete(id:)`
    /// uses the same process-wide lock, so a delete cannot land between the
    /// existence check and save and then be accidentally resurrected.
    func updateIfPresent(
        id: UUID,
        matching predicate: (TranscriptSession) -> Bool,
        mutate: (inout TranscriptSession) -> Void
    ) throws -> TranscriptSession? {
        let updated: TranscriptSession? = try withOperationLock {
            guard var session = loadWithoutLock(id: id), predicate(session) else {
                return nil
            }
            mutate(&session)
            try saveWithoutNotification(session)
            return session
        }
        if updated != nil {
            NotificationCenter.default.post(
                name: .meetingTranscriptStoreDidChange,
                object: nil
            )
        }
        return updated
    }

    public func list() -> [TranscriptSession] {
        guard let entries = try? FileManager.default.contentsOfDirectory(
            at: rootDirectory, includingPropertiesForKeys: nil
        ) else { return [] }
        let sessions = entries.compactMap { dir -> TranscriptSession? in
            guard let id = UUID(uuidString: dir.lastPathComponent) else { return nil }
            return load(id: id)
        }
        return sessions.sorted { $0.startedAt > $1.startedAt }
    }

    public func delete(id: UUID) throws {
        try withOperationLock {
            try FileManager.default.removeItem(at: sessionDirectory(id: id))
        }
        NotificationCenter.default.post(name: .meetingTranscriptStoreDidChange, object: nil)
    }

    public func purgeAudio(for id: UUID) throws {
        let fileManager = FileManager.default
        for url in m4aFiles(in: sessionDirectory(id: id)) {
            try fileManager.removeItem(at: url)
        }
        // chunk dirs are also raw audio; drop them along with the source files.
        for dir in [chunksDirectory(id: id),
                    chunksDirectory(id: id, source: .local),
                    chunksDirectory(id: id, source: .remote)] {
            if fileManager.fileExists(atPath: dir.path) {
                try fileManager.removeItem(at: dir)
            }
        }
        _ = try updateIfPresent(
            id: id,
            matching: { _ in true },
            mutate: { $0.audioRetained = false }
        )
    }

    /// Deletes all m4a artifacts and chunk directories for every completed session
    /// whose `endedAt` is older than `cutoff`. Transcript JSON is preserved.
    /// Returns the number of sessions whose audio was purged.
    @discardableResult
    public func purgeAudioOlderThan(_ cutoff: Date) -> Int {
        var purged = 0
        for session in list() {
            guard let endedAt = session.endedAt, endedAt < cutoff else { continue }
            // Only purge terminal-state sessions.
            switch session.status {
            case .completed, .cancelled, .failed:
                break
            case .recording, .chunking, .transcribing:
                continue
            }
            // Older Vox builds sometimes flipped this flag after deleting only
            // the three primary files, leaving trimmed/mixed/chunk artifacts.
            // Inspect disk when the flag is false so the retention sweep repairs
            // those historical partial purges instead of skipping them forever.
            guard session.audioRetained || hasAudioArtifacts(for: session.id) else {
                continue
            }
            if (try? purgeAudio(for: session.id)) != nil { purged += 1 }
        }
        return purged
    }

    /// Total bytes of all meeting audio artifacts under the transcript root.
    public func audioDiskBytes() -> UInt64 {
        var total: UInt64 = 0
        for url in m4aFiles(in: rootDirectory) {
            guard
                let values = try? url.resourceValues(forKeys: [.fileSizeKey]),
                let size = values.fileSize,
                size > 0
            else { continue }
            total += UInt64(size)
        }
        return total
    }

    private func hasAudioArtifacts(for id: UUID) -> Bool {
        if !m4aFiles(in: sessionDirectory(id: id)).isEmpty {
            return true
        }
        return [
            chunksDirectory(id: id),
            chunksDirectory(id: id, source: .local),
            chunksDirectory(id: id, source: .remote),
        ].contains { FileManager.default.fileExists(atPath: $0.path) }
    }

    private func m4aFiles(in directory: URL) -> [URL] {
        guard let enumerator = FileManager.default.enumerator(
            at: directory,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: []
        ) else { return [] }

        var files: [URL] = []
        for case let url as URL in enumerator {
            guard url.pathExtension.caseInsensitiveCompare("m4a") == .orderedSame else {
                continue
            }
            guard
                let values = try? url.resourceValues(forKeys: [.isRegularFileKey]),
                values.isRegularFile == true
            else { continue }
            files.append(url)
        }
        return files
    }

    /// Cold-recovery sweep: any session left in an in-flight state from a prior process
    /// (recording, chunking, transcribing) is reset to `.failed` so the UI shows a clean
    /// terminal state rather than a stuck spinner. Idempotent.
    public func recoverInFlightSessions() {
        for session in list() {
            switch session.status {
            case .recording, .chunking, .transcribing:
                _ = try? updateIfPresent(
                    id: session.id,
                    matching: {
                        [.recording, .chunking, .transcribing].contains($0.status)
                    },
                    mutate: {
                        $0.status = .failed
                        if $0.endedAt == nil { $0.endedAt = Date() }
                    }
                )
            case .completed, .cancelled, .failed:
                break
            }
        }
    }

    private func withOperationLock<T>(_ body: () throws -> T) rethrows -> T {
        Self.operationLock.lock()
        defer { Self.operationLock.unlock() }
        return try body()
    }
}
